name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install --frozen-lockfile

      - name: Clean cache and build
        run: |
          npx vite clean
          npm run docs:build

      - name: Debug - Check build output
        run: |
          echo "=== 检查构建输出 ==="
          ls -la .vitepress/dist/
          echo "=== 文件数量 ==="
          find .vitepress/dist -type f | wc -l
          echo "=== index.html 详情 ==="
          ls -la .vitepress/dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
