name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install --frozen-lockfile

      - name: Build
        run: npm run docs:build

      # 添加调试步骤
      - name: Debug - Check build output
        run: |
          echo "=== 检查构建输出 ==="
          ls -la
          echo "=== 检查 .vitepress 目录 ==="
          ls -la .vitepress/
          echo "=== 检查 dist 目录 ==="
          ls -la .vitepress/dist/
          echo "=== 检查 index.html ==="
          find . -name "index.html" -type f

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
